### ISSUE TITLE
Some links are not properly displayed in the new interface

### ISSUE THREAD

**Issue by condekind** [boardgamers/boardgamers-mono#19]
The links for auction and variants in https://testdev.boardgamers.space/new-game/gaia-project appear as:

![image](https://user-images.githubusercontent.com/8984737/117161295-2c039a80-ad98-11eb-9105-75eae621430c.png)

**Comment by coyotte508** [comment]
Fixed by https://github.com/boardgamers/boardgamers-mono/commit/94b869562c304e0dc509cf42226473f841948e1d
