### ISSUE TITLE
Don't mark system messages as unread

### ISSUE THREAD

**Issue by RobertBolender** [boardgamers/boardgamers-mono#21]
Minor annoyance: I dislike the "unread message" indicator that informs me that the game has started or that a new round has begun. I would prefer if that indicator _only_ indicated whether a human had sent a message that I haven't read yet. Could we consider this change?

**Comment by coyotte508** [comment]
Transferred the issue to the site.

On the new site (currently in beta), it's an easy fix: https://github.com/boardgamers/boardgamers-mono/blob/master/webapp-svelte/src/components/ChatRoom.svelte
