### ISSUE TITLE
Player should be immediately added to the player list when joining a game

### ISSUE THREAD

**Issue by RobertBolender** [boardgamers/boardgamers-mono#22]
Currently, I have to refresh the page in order to see myself in the player list. If I attempt to click the "Join" button a second time I'll get an error because I'm already in the game.

**Comment by coyotte508** [comment]
It's the case in the beta site - linked in the announcement (and going live this week-end!)

**Comment by RobertBolender** [comment]
I should have mentioned in the original report, this was still the case for me on the beta site.

**Comment by RobertBolender** [comment]
I do see that when *others* join a game, that appears without a refresh. My initial report is about when *I* join a game.

**Comment by coyotte508** [comment]
Yes, it doesn't happen for me. Maybe it's a race condition where it happens sometimes and others not

**Comment by RobertBolender** [comment]
Haven't played in a while, so no repro case.
