### ISSUE TITLE
Container icon shows undefined (only when logged out) on games list

### ISSUE THREAD

**Issue by LucasAMello** [boardgamers/boardgamers-mono#27]
![image](https://user-images.githubusercontent.com/35138524/126367159-2e0e4b1d-d582-4930-99ea-955d80b6d419.png)
![image](https://user-images.githubusercontent.com/35138524/126367200-e6b3d242-89e1-45e3-a3fd-8ac54ad48f70.png)

**Comment by coyotte508** [comment]
It's because the game is private for now

**Comment by coyotte508** [comment]
It's fixed! :)
